#!/bin/bash

run_resnet18 () {
  for N in 1 2 3 4 5
  do
     nc run -C GPUALG python main.py --norm_loss --model_name resnet18 --gptq  --temperature_learning --disable_activation_quantization --lr 0.05 --bias_learning --weights_nbits 4 --jacobian_weights --group ablation --n_images 2048 --gptq_num_calibration_iter 10000
  done
}

run_resnet18