#!/bin/bash
# shellcheck disable=SC2037
export GENERAL_COMMAND="--is_symmetric" #
# shellcheck disable=SC2037
export GPTQ_COMMAND=" --gptq --bias_learning --n_images 1024 --gptq_num_calibration_iter 80000 --maximal_temp 1.0 --minimal_temp 0.5 --temperature_learning --quantization_parameters_learning --jacobian_weights" #
# shellcheck disable=SC2037
export GROUP=log_norm_zero-new-baseline
export GROUP_MP=mpruns-new_res-last
export GROUP_MP_GPTQ=new_res_mp_update
export GROUP_MP_TOTAL_GPTQ=new_res_mp_total


run_gptq_only() {
  # $1
  # $2
  #  2 3 4 5

  for N in 1 2 3 4 5
  do
     nc run -C GPUALG python main.py  --model_name $1 --gamma_temperature $5 --lr $2 --weights_nbits $7 --group $GROUP-$1-$2-$3-$4-$5-$6-$7-$8 $GENERAL_COMMAND $GPTQ_COMMAND --lr_bias $3 --lr_quantization_param $4 --random_seed $N --gumbel_scale $6 --m8 $8 --m4 $9
  done
}

run_gptq_only_low() {
  # $1
  # $2
  #  2 3 4 5

  for N in 1 2 3 4 5
  do
     nc run -C GPUALG python main.py  --model_name $1 --gamma_temperature $5 --lr $2 --weights_nbits $7 --group $GROUP-$1-$2-$3-$4-$5-$6-$7-$8 $GENERAL_COMMAND $GPTQ_COMMAND --lr_bias $3 --lr_quantization_param $4 --random_seed $N --gumbel_scale $6 --m8 $8 --m4 $9 --disable_activation_quantization
  done
}

run_only_mp () {
  # $1 cr
  # $2 model

  for N in 1 2 3 4 5
  do
    nc run -C GPUALG2 python main.py --model_name $2 --use_grad_based_weights --mixed_precision --weights_cr $1 --group MP-ONLY-$2-$3 --random_seed $N  $GENERAL_COMMAND
  done
}

run_only_mp_aw () {
  # $1 cr
  # $2
  # $2 model

  for N in 1 2 3 4 5
  do
    nc run -C GPUALG python main.py --model_name $2 --use_grad_based_weights --mixed_precision --total_cr $1 --group MP-ONLY-AllBits --random_seed $N  $GENERAL_COMMAND --mp_all_bits
  done
}



run_only_mp_total () {
  # $1 cr
  # $2 model

  for N in 1 2 3 4 5
  do
    nc run -C GPUALG python main.py --model_name $2 --use_grad_based_weights --mixed_precision --total_cr $1 --group MP-TOTAL-$1-$2 --random_seed $N  $GENERAL_COMMAND
  done
}


run_mp () {
  # $1 cr
  # 2 3 4 5
  for N in 1 2 3 4 5
  do
    nc run -C GPUALG python main.py --model_name $1 --mixed_precision_override --mixed_precision --group $GROUP_MP_GPTQ-one_m --random_seed $N  $GENERAL_COMMAND $GPTQ_COMMAND  --weights_cr $2  --lr $3 --lr_bias $4 --lr_quantization_param $5 --gamma_temperature $6  --gumbel_scale $7 #--m8 0 --m7 0 --m6 0 --mp_all_bits
  done
}

run_mp_zero_m () {
  # $1 cr
  # 2 3 4 5
  for N in 1 2 3 4 5
  do
    nc run -C GPUALG python main.py --model_name $1 --mixed_precision_override --mixed_precision --group $GROUP_MP_GPTQ-zero_m  --random_seed $N  $GENERAL_COMMAND $GPTQ_COMMAND  --weights_cr $2  --lr $3 --lr_bias $4 --lr_quantization_param $5 --gamma_temperature $6  --gumbel_scale $7 --m8 0 --m7 0 --m6 0 #--m8 0 --m7 0 --m6 0 --mp_all_bits
  done
}

run_mp_act_weights () {
  # $1 cr
  #
  for N in 1 2 3 4 5
  do
    nc run -C GPUALG2 python main.py --model_name $1 --mixed_precision_override --mixed_precision --group $GROUP_MP_GPTQ-AllBits-$1 --random_seed $N  $GENERAL_COMMAND $GPTQ_COMMAND  --total_cr $2    --lr $3 --lr_bias $4 --lr_quantization_param $5 --gamma_temperature $6  --gumbel_scale $7 --mp_all_bits #--m8 0 --m7 0 --m6 0
  done
}

run_mp_total () {
  # $1 cr
  #
  for N in 1 2 3 4 5
  do
    nc run -C GPUALG python main.py --model_name $1 --mixed_precision_override --mixed_precision --group $GROUP_MP_TOTAL_GPTQ-$3-$4-$5-$6-$7-$8 --random_seed $N  $GENERAL_COMMAND $GPTQ_COMMAND  --total_cr $2  --lr $3 --lr_bias $4 --lr_quantization_param $5 --gamma_temperature $6  --gumbel_scale $7 --m8 $8
  done
}


########################################
# Baseline config
########################################



#run_gptq_only mbv2 0.3 1e-4 1e-2 0.0 0.5 4 0 0
#run_gptq_only regnetx_006 0.3 1e-2 1e-2 0.1 0.5 4 0 0
#run_gptq_only regnetx_006 0.3 1e-4 1e-3 0.1 0.4 3 0 0
#run_gptq_only regnetx_006 0.3 1e-4 1e-3 0.1 0.7 3 0 0
#run_gptq_only regnetx_006 0.3 1e-4 1e-3 0.1 0.3 3 0 0
#run_gptq_only regnetx_006 0.3 1e-4 1e-3 0.1 0.6 3 0 0
#run_gptq_only regnetx_006 0.3 1e-4 1e-3 0.1 0.5 2 0 0
#
#run_gptq_only regnetx_006 0.3 1e-4 1e-3 0.05 0.5 3 0 0
#run_gptq_only regnetx_006 0.3 1e-4 1e-3 0.05 0.5 2 0 0
run_gptq_only mbv2 0.3 1e-3 1e-3 0.0 0.3 4 0 0
#run_gptq_only mbv2 0.3 1e-3 1e-3 0.0 0.4 4 0 0
#run_gptq_only mbv2 0.3 1e-3 1e-3 0.0 0.6 4 0 0
#run_gptq_only mbv2 0.3 1e-3 1e-3 0.0 0.7 4 0 0
#run_gptq_only resnet18 0.7 1e-3 1e-3 0.1 0.5 4 0 0
#run_gptq_only resnet18 0.6 1e-3 1e-3 0.1 0.5 4 0 0
#run_gptq_only resnet18 0.5 1e-3 1e-3 0.1 0.5 4 0 0
#run_gptq_only resnet18 0.4 1e-3 1e-3 0.1 0.5 4 0 0
#run_gptq_only resnet18 0.2 1e-3 1e-3 0.1 0.5 4 0 0
#run_gptq_only resnet18 0.1 1e-3 1e-3 0.1 0.5 4 0 0
#run_gptq_only resnet18 0.05 1e-3 1e-3 0.1 0.5 4 0 0


#run_gptq_only mbv2 0.1 1e-4 1e-2 0.0 0.85 3 0 0
#run_gptq_only regnetx_006 0.05 1e-4 1e-3 0.1 0.5 4
#run_gptq_only tv_resnet50 0.3 1e-3 1e-3 0.1 0.5 4 0 0
#run_gptq_only resnet18 0.3 1e-4 1e-2 0.05 0.7 4 0 0
#run_gptq_only resnet18 0.3 1e-4 1e-2 0.05 0.6 4 0 0
#run_gptq_only resnet18 0.3 1e-4 1e-2 0.05 0.5 4 0 0
#run_gptq_only resnet18 0.3 1e-4 1e-2 0.05 0.8 4 0 0
#run_gptq_only resnet18 0.3 1e-4 1e-2 0.05 0.9 4 0 0


########################################
# MP RegNet Total
########################################
#run_only_mp_total 6 regnetx_006
#run_only_mp_total 7 regnetx_006
#run_only_mp_total 8.8 regnetx_006
#run_only_mp_total 9.8 regnetx_006
#run_only_mp_total 11 regnetx_006
#run_only_mp_total 12.5 regnetx_006
########################################
# MP ResMet
########################################
#run_only_mp 8 resnet18
#run_only_mp 8.8 resnet18
#run_only_mp 9.8 resnet18
#run_only_mp 11 resnet18
#run_only_mp 12.5 resnet18
########################################
# MP ResNet50
########################################
#run_only_mp_aw 12.8  tv_resnet50
########################################
# ResNet50 MP Join
########################################
#run_mp_act_weights tv_resnet50 12.8 0.3 1e-4 1e-3 0.05 0.5
#run_mp_act_weights tv_resnet50 13.1 0.3 1e-4 1e-3 0.05 0.75 8
########################################
# MP MBV2
########################################
#run_only_mp 8 mbv2 dense2
#run_only_mp 8.8 mbv2 dense2
#run_only_mp 9.8 mbv2 dense2
#run_only_mp 11 mbv2 dense2
#run_only_mp 12.5 mbv2 dense2
########################################
# MP Total MBV2
########################################
#run_only_mp_total 8 mbv2
#run_only_mp_total 8.8 mbv2
#run_only_mp_total 9.8 mbv2
#run_only_mp_total 11 mbv2
#run_only_mp_total 12.5 mbv2
########################################
# MP+GPTQ MBV2
########################################
#run_mp mbv2 8 0.3 1e-4 1e-3 0.05 0.5
#run_mp mbv2 8 0.3 1e-4 1e-3 0.1 0.5
#run_mp mbv2 8 0.3 1e-4 1e-3 0.15 0.5
#run_mp mbv2 8.8 0.3 1e-4 1e-3 0.0 0.5
########################################
# MP+GPTQ ResNet18
########################################
#run_mp regnetx_006 8 0.3 1e-4 1e-3 0.1 0.5
#run_mp regnetx_006 8.8 0.3 1e-4 1e-3 0.1 0.5
#run_mp regnetx_006 9.8 0.3 1e-4 1e-3 0.1 0.5
#run_mp regnetx_006 11 0.3 1e-4 1-3 0.1 0.5
#run_mp regnetx_006 12.5 0.3 1e-4 1e-3 0.1 0.5

########################################
# MP ResNet + GPTQ
########################################
#run_mp resnet18 8 0.1 1e-4 1e-3 0.1 0.55
#run_mp resnet18 8 0.1 1e-4 1e-3 0.1 0.65
#run_mp resnet18 8 0.1 1e-4 1e-3 0.1 0.4
#run_mp resnet18 8 0.1 1e-4 1e-3 0.1 0.7
#run_mp resnet18 8.8 0.3 1e-4 1e-3 0.1 0.6
#run_mp resnet18 9.8 0.3 1e-4 1e-3 0.1 0.6
#run_mp resnet18 11 0.3 1e-4 1e-3 0.1 0.6
#run_mp resnet18 12.5 0.3 1e-4 1e-3 0.1 0.6
#
#run_mp_zero_m resnet18 8 0.1 1e-4 1e-3 0.1 0.55
#run_mp_zero_m resnet18 8 0.1 1e-4 1e-3 0.1 0.65
#run_mp_zero_m resnet18 8 0.1 1e-4 1e-3 0.1 0.6
#run_mp_zero_m resnet18 8.8 0.3 1e-4 1e-3 0.1 0.6
#run_mp_zero_m resnet18 9.8 0.3 1e-4 1e-3 0.1 0.65
#run_mp_zero_m resnet18 11 0.3 1e-4 1e-3 0.1 0.6
#run_mp_zero_m resnet18 12.5 0.3 1e-4 1e-3 0.1 0.6

########################################
# MP RegNet
########################################
#run_only_mp 8 regnetx_006
#run_only_mp 8.8 regnetx_006
########################################
# MP RegNet + GPTQ
########################################
#run_mp regnetx_006 8 0.05 3e-4 3e-3 0.1 0.5 2
#run_mp regnetx_006 8.8 0.05 3e-4 3e-3 0.1 0.5 2
#run_mp regnetx_006 9.8 0.05 3e-4 3e-3 0.1 0.5 2
#run_mp regnetx_006 11 0.05 3e-4 3e-3 0.1 0.5 2
#run_mp regnetx_006 12.5 0.05 3e-4 3e-3 0.1 0.5 1
########################################
# MP RegNet + GPTQ + Total
########################################
#run_mp_total regnetx_006 6 0.05 3e-4 3e-3 0.1 0.5 2
#run_mp_total regnetx_006 7 0.05 3e-4 3e-3 0.1 0.5 2
#run_mp_total regnetx_006 8 0.05 3e-4 3e-3 0.1 0.5 2
#run_mp_total regnetx_006 8.8 0.05 3e-4 3e-3 0.1 0.5 2
#run_mp_total regnetx_006 9.8 0.05 3e-4 3e-3 0.1 0.5 2
#run_mp_total regnetx_006 11 0.05 3e-4 3e-3 0.1 0.5 2
#run_mp_total regnetx_006 12.5 0.05 3e-4 3e-3 0.1 0.5 2