#!/bin/bash
function_name () {
  # $1 cr
  # $2 m8
  for N in 1 2 3 4 5
  do
     nc run -C GPUALG python main.py --norm_loss --model_name resnet18 --mixed_precision_override --use_grad_based_weights --mixed_precision --weights_cr $1 --gptq --temperature_learning --n_images 1024 --gptq_num_calibration_iter 20000  --lr 0.05 --lr_rest 1e-4 --bias_learning --weights_nbits 4 --jacobian_weights --m8 $2 --group $1-mp-$2
  done
}

function_name 8 2
function_name 8 3
function_name 8 4
# function_name 8.8
# function_name 9.8
# function_name 11
# function_name 12.5
# function_name 14.66
#nc run -C GPUALG python main.py --model_name resnet18 --mixed_precision_override --use_grad_based_weights --mixed_precision --weights_cr 8 --group mpbaseresnet18wtest
#nc run -C GPUALG python main.py --model_name resnet18 --mixed_precision_override --use_grad_based_weights --mixed_precision --weights_cr 8.8 --group mpbaseresnet18wtest
#nc run -C GPUALG python main.py --model_name resnet18 --mixed_precision_override --use_grad_based_weights --mixed_precision --weights_cr 9.8 --group mpbaseresnet18wtest
#nc run -C GPUALG python main.py --model_name resnet18 --mixed_precision_override --use_grad_based_weights --mixed_precision --weights_cr 11 --group mpbaseresnet18wtest
#nc run -C GPUALG python main.py --model_name resnet18 --mixed_precision_override --use_grad_based_weights --mixed_precision --weights_cr 12.5 --group mpbaseresnet18wtest
#nc run -C GPUALG python main.py --model_name resnet18 --mixed_precision_override --use_grad_based_weights --mixed_precision --weights_cr 14.66 --group mpbaseresnet18wtest