#!/bin/bash
# nc run -C GPUALG python main.py --model_name resnet50 --gptq --temperature_learning --disable_activation_quantization --n_images 1024 --gptq_num_calibration_iter 20000  --lr 0.1 --lr_rest 1e-4 --bias_learning --weights_nbits 4 --jacobian_weights
# nc run -C GPUALG python main.py --model_name mbv2 --gptq --temperature_learning --disable_activation_quantization --n_images 1024 --gptq_num_calibration_iter 20000  --lr 0.1 --lr_rest 1e-4 --bias_learning --weights_nbits 4 --jacobian_weights
# nc run -C GPUALG python main.py --model_name resnet18 --gptq --temperature_learning --disable_activation_quantization --n_images 1024 --gptq_num_calibration_iter 20000  --lr 0.1 --lr_rest 1e-4 --bias_learning --weights_nbits 4 --jacobian_weights
# nc run -C GPUALG python main.py --model_name resnet50 --gptq --temperature_learning --disable_activation_quantization --n_images 1024 --gptq_num_calibration_iter 20000  --lr 0.2 --lr_rest 1e-4 --bias_learning --weights_nbits 4 --jacobian_weights
# nc run -C GPUALG python main.py --model_name mbv2 --gptq --temperature_learning --disable_activation_quantization --n_images 1024 --gptq_num_calibration_iter 20000  --lr 0.2 --lr_rest 1e-4 --bias_learning --weights_nbits 4 --jacobian_weights
# nc run -C GPUALG python main.py --model_name resnet18 --gptq --temperature_learning --disable_activation_quantization --n_images 1024 --gptq_num_calibration_iter 20000  --lr 0.2 --lr_rest 1e-4 --bias_learning --weights_nbits 4 --jacobian_weights
# nc run -C GPUALG python main.py --model_name resnet50 --gptq --temperature_learning --disable_activation_quantization --n_images 1024 --gptq_num_calibration_iter 20000  --lr 0.4 --lr_rest 1e-4 --bias_learning --weights_nbits 4 --jacobian_weights
# nc run -C GPUALG python main.py --model_name mbv2 --gptq --temperature_learning --disable_activation_quantization --n_images 1024 --gptq_num_calibration_iter 20000  --lr 0.4 --lr_rest 1e-4 --bias_learning --weights_nbits 4 --jacobian_weights
# nc run -C GPUALG python main.py --model_name resnet18 --gptq --temperature_learning --disable_activation_quantization --n_images 1024 --gptq_num_calibration_iter 20000  --lr 0.4 --lr_rest 1e-4 --bias_learning --weights_nbits 4 --jacobian_weights
#nc run -C GPUALG python main.py --model_name resnet18 --gptq --temperature_learning --disable_activation_quantization --n_images 1024 --gptq_num_calibration_iter 20000  --lr 0.2 --lr_rest 1e-4 --bias_learning --weights_nbits 4 --jacobian_weights --group lr0.2
#nc run -C GPUALG python main.py --model_name resnet18 --gptq --temperature_learning --disable_activation_quantization --n_images 1024 --gptq_num_calibration_iter 20000  --lr 0.2 --lr_rest 1e-4 --bias_learning --weights_nbits 4 --jacobian_weights --group lr0.2
#nc run -C GPUALG python main.py --model_name resnet18 --gptq --temperature_learning --disable_activation_quantization --n_images 1024 --gptq_num_calibration_iter 20000  --lr 0.2 --lr_rest 1e-4 --bias_learning --weights_nbits 4 --jacobian_weights --group lr0.2
#nc run -C GPUALG python main.py --model_name resnet18 --gptq --temperature_learning --disable_activation_quantization --n_images 1024 --gptq_num_calibration_iter 20000  --lr 0.2 --lr_rest 1e-4 --bias_learning --weights_nbits 4 --jacobian_weights --group lr0.2
#nc run -C GPUALG python main.py --model_name resnet18 --gptq --temperature_learning --disable_activation_quantization --n_images 1024 --gptq_num_calibration_iter 20000  --lr 0.2 --lr_rest 1e-4 --bias_learning --weights_nbits 4 --jacobian_weights --group lr0.2
# nc run -C GPUALG python main.py --norm_loss --model_name mbv2 --gptq --temperature_learning --disable_activation_quantization --n_images 1024 --gptq_num_calibration_iter 20000  --lr 0.2 --lr_rest 1e-4 --bias_learning --weights_nbits 4 --jacobian_weights --group wnormlr02
# nc run -C GPUALG python main.py --norm_loss --model_name mbv2 --gptq --temperature_learning --disable_activation_quantization --n_images 1024 --gptq_num_calibration_iter 20000  --lr 0.2 --lr_rest 1e-4 --bias_learning --weights_nbits 4 --jacobian_weights --group wnormlr02
# nc run -C GPUALG python main.py --norm_loss --model_name mbv2 --gptq --temperature_learning --disable_activation_quantization --n_images 1024 --gptq_num_calibration_iter 20000  --lr 0.2 --lr_rest 1e-4 --bias_learning --weights_nbits 4 --jacobian_weights --group wnormlr02
# nc run -C GPUALG python main.py --norm_loss --model_name mbv2 --gptq --temperature_learning --disable_activation_quantization --n_images 1024 --gptq_num_calibration_iter 20000  --lr 0.2 --lr_rest 1e-4 --bias_learning --weights_nbits 4 --jacobian_weights --group wnormlr02
# nc run -C GPUALG python main.py --norm_loss --model_name mbv2 --gptq --temperature_learning --disable_activation_quantization --n_images 1024 --gptq_num_calibration_iter 20000  --lr 0.2 --lr_rest 1e-4 --bias_learning --weights_nbits 4 --jacobian_weights --group wnormlr02
# nc run -C GPUALG python main.py --norm_loss --model_name resnet18 --gptq --temperature_learning --disable_activation_quantization --n_images 1024 --gptq_num_calibration_iter 20000  --lr 0.05 --lr_rest 1e-4 --bias_learning --weights_nbits 4 --jacobian_weights --group test_m0
#nc run -C GPUALG python main.py --norm_loss --model_name resnet18 --gptq --temperature_learning --disable_activation_quantization --lr 0.05 --lr_rest 1e-4 --bias_learning --weights_nbits 4 --jacobian_weights --group test_qpl
#nc run -C GPUALG python main.py --norm_loss --model_name resnet18 --gptq --temperature_learning --disable_activation_quantization --lr 0.05 --lr_rest 1e-3 --bias_learning --weights_nbits 4 --jacobian_weights --group test_qpl
#nc run -C GPUALG python main.py --norm_loss --model_name resnet18 --gptq --temperature_learning --disable_activation_quantization --lr 0.05 --lr_rest 1e-2 --bias_learning --weights_nbits 4 --jacobian_weights  --group test_qpl
#nc run -C GPUALG python main.py --norm_loss --model_name resnet18 --gptq --temperature_learning --disable_activation_quantization --lr 0.05 --lr_rest 1e-2 --bias_learning --weights_nbits 4 --jacobian_weights --group test_qpl
#nc run -C GPUALG python main.py --norm_loss --model_name resnet18 --gptq --temperature_learning --disable_activation_quantization --lr 0.05 --lr_rest 1e-2 --bias_learning --weights_nbits 4 --jacobian_weights ---group test_qpl
#nc run -C GPUALG python main.py --norm_loss --model_name resnet18 --gptq --temperature_learning --disable_activation_quantization --lr 0.05 --lr_rest 1e-2 --bias_learning --weights_nbits 4 --jacobian_weights --group test_qpl
#nc run -C GPUALG python main.py --norm_loss --model_name resnet18 --gptq --temperature_learning --disable_activation_quantization --lr 0.05 --lr_rest 1e-1 --bias_learning --weights_nbits 4 --jacobian_weights --group test_qpl
#nc run -C GPUALG python main.py --norm_loss --model_name resnet18 --gptq --temperature_learning --disable_activation_quantization --lr 0.05 --lr_rest 1e-4 --bias_learning --weights_nbits 4 --jacobian_weights --group test_qpl
#nc run -C GPUALG python main.py --norm_loss --model_name resnet18 --gptq --temperature_learning --disable_activation_quantization --lr 0.05 --lr_rest 1e-4 --bias_learning --weights_nbits 4 --jacobian_weights --group test_qpl
#nc run -C GPUALG python main.py --norm_loss --model_name resnet18 --gptq --temperature_learning --disable_activation_quantization --lr 0.05 --lr_rest 1e-4 --bias_learning --weights_nbits 4 --jacobian_weights --group test_qpl
run_resnet18 () {
  for N in 1 2 3 4 5
  do
     nc run -C GPUALG python main.py --norm_loss --model_name resnet18 --gptq  --temperature_learning --disable_activation_quantization --lr 0.05 --bias_learning --weights_nbits 4 --jacobian_weights --group base-line --n_images 2048 --gptq_num_calibration_iter 40000
  done
}

run_resnet50 () {
  for N in 1 2 3 4 5
  do
     nc run -C GPUALG python main.py --norm_loss --model_name resnet50 --gptq --temperature_learning --disable_activation_quantization --lr 0.05 --bias_learning --weights_nbits 4 --jacobian_weights --group base-line --n_images 2048 --gptq_num_calibration_iter 40000
  done
}

run_mbv2 () {
  for N in 1 2 3 4 5
  do
     nc run -C GPUALG python main.py  --model_name mbv2 --gptq --temperature_learning --disable_activation_quantization --lr 0.1 --bias_learning --weights_nbits 4 --jacobian_weights --norm_loss --group base-line --n_images 2048 --gptq_num_calibration_iter 40000
  done
}


run_resnet18
run_resnet50
run_mbv2